---
deployment:
  tasks:
    - export DEPLOYPATH=/home/carlinxi/partner.carlinx.id
    - export REPOPATH=/home/carlinxi/repositories/carlinx
    - /bin/cp -u ${REPOPATH}/app/Controllers/* ${DEPLOYPATH}/ci4_core/app/Controllers/
    - /bin/cp -u ${REPOPATH}/app/Views/* ${DEPLOYPATH}/ci4_core/app/Views/
    - /bin/cp -u ${REPOPATH}/app/Models/* ${DEPLOYPATH}/ci4_core/app/Models/
    - /bin/cp -u ${REPOPATH}/public/* ${DEPLOYPATH}