---
deployment:
  tasks:
    - export DEPLOYPATH=/home/carlinx/partner.carlinx.id
    - /bin/cp -R app/* $DEPLOYPATH/app/
    - /bin/cp -R public/* $DEPLOYPATH/public/
    - /bin/cp -R writable/* $DEPLOYPATH/writable/
    - /bin/cp -R Controllers/* $DEPLOYPATH/Controllers/
    - /bin/cp -R Views/* $DEPLOYPATH/Views/
    - /bin/cp serviceWorker.js $DEPLOYPATH/
    - /bin/cp manifest.json $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/
    - /bin/cp robots.txt $DEPLOYPATH/